const KEY='finance-app-v3';
const categories={receita:['Salário','PIX recebido','Freelance','Vendas','Investimentos','Reembolso','Outras receitas'],despesa:['Alimentação','Transporte','Moradia','Saúde','Educação','Lazer','Compras','Assinaturas','Contas','Cartão','Família','Outras despesas']};
const rules=[['salario|salário|pagamento|ordenado','Salário','receita'],['pix|transferencia recebida|recebi','PIX recebido','receita'],['freela|freelance|serviço|servico','Freelance','receita'],['mercado|supermercado|atacado|carrefour|assai|assaí|bompreço|bompreco|ifood|restaurante|lanche|pizza|padaria|comida|coca','Alimentação','despesa'],['uber|99|ônibus|onibus|gasolina|combustivel|combustível|posto|moto|mecânico|mecanico|embreagem','Transporte','despesa'],['aluguel|condominio|condomínio|casa|energia|celpe|neoenergia|água|agua|internet|wifi','Moradia','despesa'],['farmacia|farmácia|remedio|remédio|consulta|medico|médico|hospital','Saúde','despesa'],['netflix|spotify|prime|disney|game pass|xbox|assinatura','Assinaturas','despesa'],['shopee|mercado livre|amazon|roupa|maquiagem|sandalia|sandália|shopping','Compras','despesa'],['cartao|cartão|fatura','Cartão','despesa'],['cinema|show|festa|jogo|lazer','Lazer','despesa'],['familia|família|namorada|ajuda','Família','despesa']];
let state=load();let deferredPrompt=null;
const $=id=>document.getElementById(id);const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{transactions:[],theme:'light'}}catch{return{transactions:[],theme:'light'}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function parseAmount(v){return Number(String(v).replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''))||0}
function today(){return new Date().toISOString().slice(0,10)}
function monthOf(date){return String(date||'').slice(0,7)}
function addMonths(dateStr,n){const d=new Date(dateStr+'T12:00:00');d.setMonth(d.getMonth()+n);return d.toISOString().slice(0,10)}
function fillCategories(){const type=$('type').value;$('category').innerHTML=categories[type].map(c=>`<option>${c}</option>`).join('')}
function guess(){const txt=$('description').value.toLowerCase();for(const [regex,cat,type] of rules){if(new RegExp(regex,'i').test(txt)){if($('type').value!==type){$('type').value=type;fillCategories()}$('category').value=cat;return}}}
function setTheme(t){state.theme=t;document.documentElement.dataset.theme=t;$('toggleTheme').textContent=t==='dark'?'☀️':'🌙';localStorage.setItem(KEY,JSON.stringify(state))}
function filtered(){const m=$('monthFilter').value;const q=$('search').value.trim().toLowerCase();return state.transactions.filter(t=>(!m||monthOf(t.date)===m)&&(!q||[t.description,t.category,t.account,t.note,t.type].join(' ').toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id)}
function totals(list){return list.reduce((a,t)=>{a.count++; if(t.type==='receita')a.income+=t.amount;else a.expense+=t.amount; return a},{income:0,expense:0,count:0})}
function byCategory(list,type){const obj={};list.filter(t=>t.type===type).forEach(t=>obj[t.category]=(obj[t.category]||0)+t.amount);return Object.entries(obj).sort((a,b)=>b[1]-a[1])}
function renderChart(elId,data){const el=$(elId);if(!data.length){el.className='bar-list empty';el.textContent=elId==='expenseChart'?'Sem despesas neste mês.':'Sem receitas neste mês.';return}el.className='bar-list';const max=Math.max(...data.map(x=>x[1]));el.innerHTML=data.map(([cat,val])=>`<div class="bar"><span>${cat}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(4,val/max*100)}%"></div></div><span class="bar-value">${money(val)}</span></div>`).join('')}
function render(){const list=filtered();const t=totals(list);$('incomeTotal').textContent=money(t.income);$('expenseTotal').textContent=money(t.expense);$('balanceTotal').textContent=money(t.income-t.expense);$('balanceTotal').className=t.income-t.expense<0?'negative':'positive';$('countTotal').textContent=t.count;renderChart('expenseChart',byCategory(list,'despesa'));renderChart('incomeChart',byCategory(list,'receita'));const tbody=$('transactionRows');tbody.innerHTML='';if(!list.length){tbody.innerHTML='<tr><td colspan="7">Nenhuma movimentação encontrada.</td></tr>';return}const tpl=$('rowTemplate');list.forEach(tr=>{const row=tpl.content.cloneNode(true);row.querySelector('.dateCell').textContent=tr.date.split('-').reverse().join('/');row.querySelector('.descCell').innerHTML=`<strong>${tr.description}</strong>${tr.note?`<br><small>${tr.note}</small>`:''}`;row.querySelector('.catCell').textContent=tr.category;row.querySelector('.accCell').textContent=tr.account||'-';row.querySelector('.typeCell').innerHTML=`<span class="pill ${tr.type}">${tr.type}</span>`;const val=row.querySelector('.valueCell');val.textContent=(tr.type==='despesa'?'- ':'+ ')+money(tr.amount);val.className+=' '+(tr.type==='despesa'?'value-expense':'value-income');row.querySelector('.deleteBtn').onclick=()=>{if(confirm('Excluir esta movimentação?')){state.transactions=state.transactions.filter(x=>x.id!==tr.id);save()}};tbody.appendChild(row)})}
function exportCsv(){const rows=[['Data','Descrição','Categoria','Conta','Tipo','Valor','Observação'],...state.transactions.map(t=>[t.date,t.description,t.category,t.account,t.type,String(t.amount).replace('.',','),t.note])];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n');download(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),'minha-planilha.csv')}
function exportJson(){download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'backup-minha-planilha.json')}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function init(){document.documentElement.dataset.theme=state.theme||'light';$('date').value=today();$('monthFilter').value=monthOf(today());fillCategories();$('type').onchange=fillCategories;$('description').oninput=guess;$('toggleTheme').onclick=()=>setTheme((state.theme||'light')==='light'?'dark':'light');$('transactionForm').onsubmit=e=>{e.preventDefault();const amount=parseAmount($('amount').value);if(amount<=0)return alert('Digite um valor maior que zero.');const n=Math.max(1,Number($('installments').value)||1);const baseAmount=Number((amount/n).toFixed(2));for(let i=0;i<n;i++){state.transactions.push({id:Date.now()+i,type:$('type').value,date:addMonths($('date').value,i),description:n>1?`${$('description').value} (${i+1}/${n})`:$('description').value,amount:i===n-1?Number((amount-baseAmount*(n-1)).toFixed(2)):baseAmount,category:$('category').value,account:$('account').value||'Carteira',note:$('note').value})}e.target.reset();$('date').value=today();$('installments').value=1;fillCategories();save()};['monthFilter','search'].forEach(id=>$(id).oninput=render);$('resetFilter').onclick=()=>{$('monthFilter').value='';$('search').value='';render()};$('exportCsv').onclick=exportCsv;$('exportJson').onclick=exportJson;$('clearAll').onclick=()=>{if(confirm('Tem certeza? Isso apaga tudo deste navegador.')){state.transactions=[];save()}};$('importJson').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!Array.isArray(data.transactions))throw Error();state=data;save();alert('Backup importado!')}catch{alert('Arquivo inválido.')}};r.readAsText(f)};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('installBtn').classList.add('hidden')}};if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');render()}
init();
